' 「後から分析したいから履歴を残しておいて」など、
' 分析のみの用途でも履歴データをデータベースに保存しておく必要はあるのでしょうか？
' => 回答：保存しておく必要はない。
' => 理由：ログファイルから解析できるから

@startuml

entity 記事 {
  ID
  --
  記事ID
  本文
  更新日
  バージョン
}

@enduml

' メリット: テーブルが1つしかないため、テーブル管理が楽
' デメリット1: 最新記事一覧を取得するのがめんどくさい。
' デメリット2: この記事テーブルを参照するコメントテーブルを作った際に記事を更新した際にコメントテーブルの参照IDも変更しないといけない
