@startuml

entity ユーザー {
  ユーザーID
  --
  名前
}

entity リマインダー {
  リマインダーID
  --
  作成者（ユーザーID）
  文面
  周期タイプ（月・曜日・日・時間）
  周期数
}

entity ユーザーリマインダー {
  送信相手（ユーザーID）
  リマインダーID
  --
  完了フラグ
}

ユーザー ||...o{ リマインダー
ユーザー ||...o{ ユーザーリマインダー
リマインダー ||...o{ ユーザーリマインダー


@enduml
