@startuml

entity ユーザー {
  ユーザーID
  --
  名前
}

entity ユーザーワークスペース {
  ユーザーID
  ワークスペースID
  --
}

entity ワークスペース {
  ワークスペースID
  --
  名前
}

entity ユーザーチャネル {
  ユーザーID
  チャネルID
  --
}

entity チャネル {
  チャネルID
  --
  ワークスペースID
  名前
}

entity メッセージ {
  メッセージID
  --
  ユーザーID
  チャネルID
  送信時間
  内容
}

entity スレッドメッセージ {
  スレッドメッセージID
  --
  ユーザーID
  メッセージID
  送信時間
  内容
}

ユーザー ||..o{ ユーザーワークスペース
ワークスペース ||..o{ ユーザーワークスペース
ユーザー ||..o{ ユーザーチャネル
チャネル ||..o{ ユーザーチャネル
ワークスペース ||..o{ チャネル
ユーザー ||..o{ メッセージ
チャネル ||..o{ メッセージ
ユーザー ||..|{ スレッドメッセージ
メッセージ ||..|{ スレッドメッセージ

@enduml
