@startuml

entity "商品" {
  商品ID
  --
  名前
  単価
}

entity "セット商品" {
  セットメニューID（商品ID）
  単品メニューID（商品ID）
  --
}

entity "注文" {
  注文ID
  --
  名前
  電話番号
  総額
  支払いフラグ
}

entity "注文詳細" {
  注文詳細ID
  --
  注文ID
  商品ID
  個数
  わさび有り
}

商品 ||..|{ セット商品
商品 ||..|{ 注文詳細
注文 ||..|{ 注文詳細

@enduml

' 論理モデルとは、システム化する業務のエンティティとリレーションを実装技術に依存しない形で行うモデリングである。
' 物理モデルとは、実装を考慮してエンティティをRDBMSのテーブルと1対1になるようモデリングしたものである。
' http://itref.fc2web.com/technology/entity_relationship_diagram.html
