' このお店ではお持ち帰りでの注文の他にUber Eatsを導入することにした。
' そこでその施策の効果を測るために注文毎のルート（お持ち帰り or Uber Eats）を知りたい。

@startuml

entity "セットメニュー" {
  セットメニューID
  --
  セットメニューカテゴリーID
  名前
  単価
}

entity "セットメニューカテゴリー" {
  セットメニューカテゴリーID
  --
  名前
}

entity "寿司" {
  寿司ID
  --
  皿単価ID
  名前
}

entity "皿単価" {
  皿単価ID
  --
  単価
}

entity "注文" {
  注文ID
  --
  ' 注文カテゴリーID
  名前
  電話番号
  支払い
  合計皿数
  合計個数
  注文タイプ
}

' entity "注文カテゴリー" {
'   注文カテゴリーID
'   --
'   注文タイプ
' }

entity "寿司注文詳細" {
  寿司注文詳細ID
  --
  注文ID
  寿司ID
  個数
  わさび抜き
  シャリサイズ
}

entity "セットメニュー注文詳細" {
  セットメニュー注文詳細ID
  --
  注文ID
  セットメニューID
  個数
  わさび抜き
}

セットメニューカテゴリー ||..o{ セットメニュー
皿単価 ||..o{ 寿司
注文 ||..o{ 寿司注文詳細
寿司注文詳細 ||..|{ 寿司
注文 ||..o{ セットメニュー注文詳細
セットメニュー注文詳細 ||..|{ セットメニュー
' 注文カテゴリー ||..o{ 注文

@enduml
