@startuml

entity ユーザー {
  ユーザーID
  --
  名前
}

entity ドキュメント {
  ドキュメントID
  --
  ユーザーID
  ディレクトリID
  保存日時
  内容
}

' 閉包テーブル
' メリット:要素の関係を別テーブルに持っているため構造を柔軟に変更することができる
' デメリット:直近の祖先、子孫の取得が複雑になる。テーブルスペースが増える、更新行が多くなるなどDBのリソース消費が大きい。
' https://qiita.com/ymstshinichiro/items/b1825719c4fb274446cc
' https://bbh.bz/2020/07/18/tree-structure-in-rdb/

entity ディレクトリ {
  ディレクトリID
  --
  ユーザーID
  名前
}

entity ディレクトリ関係 {
  親ディレクトリID
  子孫ディレクトリID
  深度
  --
}

ユーザー ||..o{ ドキュメント
ユーザー ||..o{ ディレクトリ
ディレクトリ ||..o{ ドキュメント

@enduml
